name: mulearn
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  device_preview: ^1.1.0
  pie_chart: ^5.3.2
  fl_chart: ^0.66.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/achie.PNG
    - assets/existing.PNG
    - assets/git.PNG
    - assets/ig.PNG
    - assets/k.PNG
    - assets/karma.PNG
    - assets/profile.PNG
    - assets/rank.PNG
    - assets/recent.PNG
    - assets/voy.PNG
